#!/bin/bash

commonname=$1
distinguishedname=$2
date=`date +%Y-%m-%d:%H:%M:%S`

echo -en "Attempting to insert admin $commonname database... \n"

query_output=$(sqlite3 /etc/glintv2/db.sqlite3 "select * from auth_user where username='$commonname'")

if [ -z "$query_output" ]
then
    sqlite3 /etc/glintv2/db.sqlite3 "insert into auth_user (password, first_name, last_name, email, is_active, is_superuser, is_staff, date_joined, username) values ('', '', '', '', 1, 1, 1, '$date', '$commonname')"
else
    sqlite3 /etc/glintv2/db.sqlite3 "Update auth_user SET is_superuser='1' where username='$commonname'"
    sqlite3 /etc/glintv2/db.sqlite3 "Update auth_user SET is_staff='1' where username='$commonname'"
fi

query_output=$(sqlite3 /etc/glintv2/db.sqlite3 "select * from glintwebui_glint_user where user_name='$commonname'")
if [ -z "$query_output" ]
then
    sqlite3 /etc/glintv2/db.sqlite3 "insert into glintwebui_glint_user (user_name, authentication_method, common_name, distinguished_name, active_project) values ('$commonname', 'x509', '$commonname', '$distinguishedname', 'default')"
else
    sqlite3 /etc/glintv2/db.sqlite3 "update glintwebui_glint_user SET authentication_method='x509', common_name='$commonname', distinguished_name='$distinguishedname' where user_name='$commonname'"
fi

echo -en "Database updated... $commonname should now have admin access to glint.\n"