install:
	@mkdir -p /usr/local/nep52accountant
	@mkdir -p /usr/local/nep52accountant/bin
	@cp ./nep52accountant /usr/local/nep52accountant/bin
	@chmod 755 /usr/local/nep52accountant/bin/nep52accountant
	@cp ./nep52accountant.init.d /etc/init.d/nep52accountant
	@chmod 755 /etc/init.d/nep52accountant
	@cp ./nep52accountant.config /etc/nep52accountant.config
	@chmod 644 /etc/nep52accountant.config
	@echo "nep52accountant installed in /usr/local/nep52accountant"
	@echo "configuration file installed at /etc/nep52accountant.config"



