version: "2"
services:
  condor:
    build: .
    image: condor
    ports: 
      - "9618:9618"
      - "40000-40500:40000-40500"
    hostname: condor_host
    privileged: true
    tty: true
    stdin_open: true
    networks:
      cs_net:
        ipv4_address: 172.28.5.2

networks:
  cs_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16



